### ISSUE TITLE
frontend: test causes error

### ISSUE THREAD

**Issue by gadjevb** [clouway-incubator/bank-with-angularjs#59]
The LogoutCtrl controller in app.spec.js causes an Error in PhantomJS, it shows this message:

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  Some of your tests did a full page reload!
```

**Comment by mgenov** [comment]
It may be caused by the usage of window.location

$location need to be used in angularjs.

**Comment by gadjevb** [comment]
@mgenov  will try it!
